// vmath: immutable, Valhalla-ready 3D math.
//
//   ./gradlew build                 JDK 21, plain records (default)
//   ./gradlew build -Pvalhalla      JDK 28 (early access), real `value record`s, --enable-preview
//
// The float sources are the single source of truth; the *d.java files are generated by
// `java tools/GenDouble.java` and `check` fails if they are stale.

plugins {
    `java-library`
}

group = "vmath"
version = "0.1.0-SNAPSHOT"

val valhalla = providers.gradleProperty("valhalla").isPresent
val baselineJdk = 21
val valhallaJdk = 28

repositories {
    mavenCentral()
}

dependencies {
    // JOML is only the test oracle; nothing in main depends on it.
    testImplementation("org.joml:joml:1.10.8")
    testImplementation(platform("org.junit:junit-bom:5.13.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(if (valhalla) valhallaJdk else baselineJdk))
    }
    withSourcesJar()
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll(listOf("-Xlint:all", "-Xlint:-preview"))
}

tasks.test {
    useJUnitPlatform()
    // Forward -Dvmath.seed / -Dvmath.trials from the command line, e.g. a nightly job with a fresh seed.
    listOf("vmath.seed", "vmath.trials").forEach { key ->
        System.getProperty(key)?.let { systemProperty(key, it) }
    }
}

// ---------------------------------------------------------------- stale-generation check

val checkGenerated by tasks.registering(Exec::class) {
    group = "verification"
    description = "Fails if the generated double-precision sources are out of date."
    val launcher = javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(baselineJdk)) }
    executable = launcher.get().executablePath.asFile.absolutePath
    args("tools/GenDouble.java", "--check")
    workingDir = projectDir
}
tasks.check { dependsOn(checkGenerated) }

// ---------------------------------------------------------------- Valhalla mode

if (valhalla) {
    val valhallaSources = layout.buildDirectory.dir("generated/valhalla/main")

    // Rewrites `public /*value*/ record X(` into `public value record X(`. Nothing else changes,
    // so both builds run the exact same code and the same tests.
    val generateValhallaSources by tasks.registering(Copy::class) {
        from("src/main/java")
        into(valhallaSources)
        filter { line: String -> line.replace("/*value*/ record", "value record") }
    }

    sourceSets.main {
        java.setSrcDirs(listOf(generateValhallaSources))
    }

    tasks.withType<JavaCompile>().configureEach {
        options.release.set(valhallaJdk)
        options.compilerArgs.add("--enable-preview")
    }
    tasks.withType<Test>().configureEach {
        jvmArgs("--enable-preview")
    }
    tasks.withType<JavaExec>().configureEach {
        jvmArgs("--enable-preview")
    }
}
